name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install @sidetree/ethereum in typescript
        run: npm i && npm t
        working-directory: typescript

      - name: Install @sidetree/ethereum in javascript
        run: npm i && npm t
        working-directory: javascript
